# Generated by Django 5.1.4 on 2025-01-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_sub_category_subcategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
