# Generated by Django 5.1.4 on 2025-01-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='index_number',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to='slides'),
        ),
    ]
