# Generated by Django 5.1.4 on 2025-01-13 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_slide_index_number_slide_link_alter_slide_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['index_number'], 'verbose_name': 'slide', 'verbose_name_plural': 'slides'},
        ),
    ]
