# Generated by Django 5.1.4 on 2025-01-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_slide_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slide',
            name='second_title',
            field=models.CharField(max_length=300),
        ),
    ]
